### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by TovenBae** [TovenBae/eyelink-parstream#133]
cronjob으로  power, event를 data simulator로 생성시 일정시간 이후 발생 오류

> Data Simulator Finished!!!!
> Error: write after end
>     at writeAfterEnd (_stream_writable.js:193:12)
>     at Socket.Writable.write (_stream_writable.js:244:5)
>     at Socket.write (net.js:661:40)
>     at Client.write (/Users/baesunghan/git/m2u/eyelink-parstream/routes/dao/parstream/m2u-parstream.js:256:15)
>     at Socket.<anonymous> (/Users/baesunghan/git/m2u/eyelink-parstream/routes/dao/parstream/m2u-parstream.js:116:18)
>     at emitOne (events.js:101:20)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:551:20)
> db not connected!!
> /Users/baesunghan/git/m2u/eyelink-parstream/node_modules/async/dist/async.js:837
>         if (fn === null) throw new Error("Callback was already called.");
>                          ^
> 
> Error: Callback was already called.
>     at /Users/baesunghan/git/m2u/eyelink-parstream/node_modules/async/dist/async.js:837:32
>     at /Users/baesunghan/git/m2u/eyelink-parstream/datasimulator/dataSimulator.js:57:22
>     at Socket.<anonymous> (/Users/baesunghan/git/m2u/eyelink-parstream/routes/dao/parstream/m2u-parstream.js:142:5)

**Comment by TovenBae** [comment]
cronjob이 주기성과 이벤트성 데이터 생성 시기가 같을 경우 parstream 객체를 공유하고서 사용하게 됨.
이때 주기성 처리 job이 완료되면서 parstream.close를 호출하면서 접속을 끊어 버림으로써 이벤트쪽 job 처리가 안되면서 발생한 오류임.
