### ISSUE TITLE
CentOS7에서 nom install시 javac 오류

### ISSUE THREAD

**Issue by TovenBae** [TovenBae/eyelink-parstream#20]
> [Toven@test-vm eyelink]$ npm install

> java@0.8.0 install /home/Toven/eyelink/node_modules/java
> node-gyp rebuild

> 
> [node-java] Error: not found: javac
> gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
>

**Comment by TovenBae** [comment]
1. Oracle JDK 설치
2. /etc/profile에 JAVA_HOME 설정

> export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b15.el7_2.x86_64
> export PATH=$PATH:$JAVA_HOME/bin:
