### ISSUE TITLE
Error] Cannot read property 'length' of null

### ISSUE THREAD

**Issue by TovenBae** [TovenBae/eyelink-parstream#58]
현재 일자의 데이타가 Parstream에 없을 경우 아래 오류 발생함. 

> /Users/baesunghan/git/m2u/eyelink-parstream/routes/util.js:29
>     console.log('util/mergeLoadedData -> date %s, data count : %s', key, _rawDataByDay[key].length);
>                                                                                            ^
> 
> TypeError: Cannot read property 'length' of null
>     at Object.mergeLoadedData (/Users/baesunghan/git/m2u/eyelink-parstream/routes/util.js:29:92)
>     at /Users/baesunghan/git/m2u/eyelink-parstream/routes/dashboard.js:66:24

**Comment by TovenBae** [comment]
데이터가 없는 날짜는 skip 하도록 처리함.
